export enum Settings {
  SCHOOL_NAME = 'SCHOOL_NAME',
  SCHOOL_ADDRESS = 'SCHOOL_ADDRESS',
  SCHOOL_PHONE = 'SCHOOL_PHONE',
  SCHOOL_EMAIL = 'SCHOOL_EMAIL',
  SCHOOL_LOGO = 'SCHOOL_LOGO',
  SCHOOL_LOGO_WEBP = 'SCHOOL_LOGO_WEBP',
  SCHOOL_LOGO_PNG = 'SCHOOL_LOGO_PNG',
}
