name: Deploy to VM Broo

on:
  push:
    branches:
      - master

jobs:
  build-and-upload-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (no cache)
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: indrafajar/pelanggaran-be-saas:latest  # Update this
          no-cache: true
    
  deploy-vm:
    runs-on: ubuntu-latest
    needs: build-and-upload-to-docker-hub
    steps:
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}
      - name: Deploy to VM
        env:
          HOST: ${{ secrets.VM_HOST }}  # Update with your VM IP
          USER: ${{ secrets.VM_USERNAME }}
          PORT: ${{ secrets.VM_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no -p "${PORT}" $USER@$HOST << 'EOF'
            docker pull indrafajar/pelanggaran-be-saas:latest
            if [ "$(docker ps -q -f name=pelanggaran-run)" ]; then
              docker stop pelanggaran-run
            fi
            if [ "$(docker ps -aq -f name=pelanggaran-run)" ]; then
              docker container rm pelanggaran-run
            fi        
            docker run -d --name pelanggaran-run --restart unless-stopped --network my-app -p 4000:3000 indrafajar/pelanggaran-be-saas:latest
            docker cp ~/pelanggaran-be/.env pelanggaran-run:/app/
            docker restart pelanggaran-run
            docker image prune -f
          EOF