name: Deploy to VM Broo

on:
  push:
    branches:
      - master2

jobs:
  build-and-upload-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (no cache)
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: indrafajar/pelanggaran-be-saas:latest  # Update this
          no-cache: true
    
  deploy-vm:
    runs-on: ubuntu-latest
    needs: build-and-upload-to-docker-hub
    steps:
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY2 }}
      - name: Deploy to VM
        env:
          HOST: ${{ secrets.VM_HOST2 }}  # Update with your VM IP
          USER: ${{ secrets.VM_USERNAME2 }}
          PORT: ${{ secrets.VM_PORT2 }}
        run: |
          ssh -o StrictHostKeyChecking=no -p "${PORT}" $USER@$HOST << 'EOF'
            podman pull docker.io/indrafajar/pelanggaran-be-saas:latest
            if [ "$(podman ps -q -f name=pelanggaran-run)" ]; then
              podman stop pelanggaran-run
            fi
            if [ "$(podman ps -aq -f name=pelanggaran-run)" ]; then
              podman container rm pelanggaran-run
            fi        
            podman run -d --name pelanggaran-run --restart unless-stopped --network my-app -p 4000:3000 docker.io/indrafajar/pelanggaran-be-saas:latest
            podman cp ~/pelanggaran-be/.env pelanggaran-run:/app/
            podman restart pelanggaran-run
            podman image prune -f
          EOF